// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFyb4qszEEsGbiIJQT-jt40Wxg432a2yA',
    appId: '1:714996467950:web:edbad191052ca9a7ba4bff',
    messagingSenderId: '714996467950',
    projectId: 'grocery-app-5340f',
    authDomain: 'grocery-app-5340f.firebaseapp.com',
    storageBucket: 'grocery-app-5340f.firebasestorage.app',
    measurementId: 'G-FM3183NWWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvYAM5cJY6GvaVYphk9O8iyj3oPVS8BUw',
    appId: '1:714996467950:android:46365a0c3271a7d7ba4bff',
    messagingSenderId: '714996467950',
    projectId: 'grocery-app-5340f',
    storageBucket: 'grocery-app-5340f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhHoBTmq7OGtwBgeS2iy4HH5C11XFuwOY',
    appId: '1:714996467950:ios:ffff54926fe5af69ba4bff',
    messagingSenderId: '714996467950',
    projectId: 'grocery-app-5340f',
    storageBucket: 'grocery-app-5340f.firebasestorage.app',
    iosBundleId: 'com.example.grocerry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhHoBTmq7OGtwBgeS2iy4HH5C11XFuwOY',
    appId: '1:714996467950:ios:ffff54926fe5af69ba4bff',
    messagingSenderId: '714996467950',
    projectId: 'grocery-app-5340f',
    storageBucket: 'grocery-app-5340f.firebasestorage.app',
    iosBundleId: 'com.example.grocerry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFyb4qszEEsGbiIJQT-jt40Wxg432a2yA',
    appId: '1:714996467950:web:f201ce1b496fb4deba4bff',
    messagingSenderId: '714996467950',
    projectId: 'grocery-app-5340f',
    authDomain: 'grocery-app-5340f.firebaseapp.com',
    storageBucket: 'grocery-app-5340f.firebasestorage.app',
    measurementId: 'G-5QB6L37G0Q',
  );
}
